# modules/thecoderpsshipping/config/routes.yml
thecoder_demo:
    path: thecoder/demo
    methods: [GET]
    defaults:
      _controller: 'Thecoderpsshipping\Controller\ThecoderpsshippingController::demoAction'

# modules/thecoderpsshipping/config/routes.yml
thecoder_add:
    path: thecoder/add
    methods: [GET, POST]
    defaults:
      _controller: 'Thecoderpsshipping\Controller\ThecoderpsshippingController::addAction'
