# modules/thecoderpsshipping/config/routes.yml
thecoder_demo:
    path: thecoder/demo
    methods: [GET]
    defaults:
      _controller: 'Thecoderpsshipping\Controller\ThecoderpsshippingController::demoAction'

# modules/thecoderpsshipping/config/routes.yml
thecoder_add:
    path: thecoder/add_city
    methods: [GET, POST]
    defaults:
      _controller: 'Thecoderpsshipping\Controller\ThecoderpsshippingController::addAction'

thecoder_list:
    path: thecoder/list
    methods: [GET, POST]
    defaults:
      _controller: 'Thecoderpsshipping\Controller\ThecoderpsshippingController::list'

thecoder_edit_city:
    path: thecoder/edit_city
    methods: [GET, POST]
    defaults:
      _controller: 'Thecoderpsshipping\Controller\ThecoderpsshippingController::list'

thecoder_delete_city:
    path: thecoder/edit_city
    methods: [GET, POST]
    defaults:
      _controller: 'Thecoderpsshipping\Controller\ThecoderpsshippingController::list'
